---
name: All in one
on: push

jobs:
  golangci-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: "1.21.4"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.55.2

  super-linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: super-linter/super-linter/slim@v5.6.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: "1.21.4"
      - run: go test -v ./...
      - run: go build ./...
